name: GilerPR

on:
  pull_request:
    types: ["opened","synchronize","reopened"]

jobs:
  main_job:
    name: main_job_name
    runs-on: ubuntu-18.04
    env:
      CI: "github_actions"
    strategy:
      fail-fast: false
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: should it be skipped?
        env:
          COMMIT_FILTER: "[skip tests]"
        run: |
          readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
          readonly local filter_count=$(echo "$last_commit_log" | grep -c "$COMMIT_FILTER" )

          if [[ "$filter_count" -eq 0 ]]; then
            echo "No skip request found"
          else
            echo "Found $COMMIT_FILTER in last commit"
            exit 78
          fi

      - name: get commit message
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})

      - name: show commit message
        run : echo $commitmsg

      - name: Testing commitmsg env setup
        if: contains( env.commitmsg , '[skip tests]' )
        run: echo "skipping tests as requested in commit message $commitmsg"

      - name: Catching the skip exit code
        if: failure()
        run: echo "Skip request found, this is the failure step"

        ################ Data Dump ################

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

        ################ Data Dump End ################
