name: GilerPR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-18.04
    env:
      CI: "github_actions"
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set Flags
        run: |
          if git log -2 --format=%s | grep '\[skip tests\]' 2>&1 > /dev/null; then
            echo ::set-env name=skip_tests::true
            # exit 78 # destroy workflow
          fi

          if git log -2 --format=%s | grep '\[run tests\]' 2>&1 > /dev/null; then
            echo ::set-env name=run_tests::true
          fi

          if git log -2 --format=%s | grep '\[run percy\]' 2>&1 > /dev/null; then
            echo ::set-env name=percy_tokens::true
          fi

          if git log -2 --format=%s | grep '\[deploy qa\]' 2>&1 > /dev/null; then
            echo ::set-env name=deploy_qa::true
          fi


      - name: Test
        if: env.skip_tests != 'true'
        run: echo "running tests with - [$percy_tokens]"

      - name: Deploy QA
        if: env.deploy_qa
        env:
          SECRETS_N_STUFF: shh
        run: echo "deploying to staging $SECRETS_N_STUFF"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: contains work?
        if: contains(github.event.head_commit.message, '[skip tests]')
        run: echo "got skip tests from the contains function"
